import { loadConfig } from "./config.js";

  export const state = {
    cfg: loadConfig(),
    currencyContext: null,
    results: [],
    scanning: false,
    stopRequested: false,
    skipCurrent: false,
    queue: null,
    sortKey: null,
    sortAsc: true,
    selectedResults: new Set(),
    bulkActionRunning: false,
    pendingOrderQuantities: new Map(),
    highestBuyPrices: new Map(),
    craftResults: [],
    craftScanning: false,
    craftActionRunning: false,
    craftStopRequested: false,
    craftQueue: null,
    surplusResults: [],
    selectedSurplusResults: new Set(),
    surplusScanning: false,
    surplusStopRequested: false,
    surplusQueue: null,
    surplusActionRunning: false,
    surplusGemPrice: null,
    grindResults: [],
    selectedGrindResults: new Set(),
    grindScanning: false,
    grindStopRequested: false,
    grindQueue: null,
    grindGemPrice: null,
    orderResults: [],
    selectedOrderResults: new Set(),
    orderSortKey: "cached",
    orderSortAsc: false,
    orderActionRunning: false,
    blLookupAppid: "",
    blLookupName: "",
  };
