import { loadConfig } from "./config.js";

  export const state = {
    cfg: loadConfig(),
    currencyContext: null,
    results: [],
    scanning: false,
    stopRequested: false,
    skipCurrent: false,
    queue: null,
    sortKey: null,
    sortAsc: true,
    selectedResults: new Set(),
    recalculationRunning: false,
    orderSubmissionRunning: false,
    automaticPricingDraft: null,
    pendingOrderQuantities: new Map(),
    highestBuyPrices: new Map(),
    marketOrderDepths: new Map(),
    craftResults: [],
    craftScanning: false,
    craftActionRunning: false,
    craftStopRequested: false,
    craftQueue: null,
    surplusResults: [],
    selectedSurplusResults: new Set(),
    surplusScanning: false,
    surplusStopRequested: false,
    surplusQueue: null,
    surplusActionRunning: false,
    surplusGemPrice: null,
    grindResults: [],
    selectedGrindResults: new Set(),
    grindScanning: false,
    grindStopRequested: false,
    grindQueue: null,
    grindGemPrice: null,
    orderResults: [],
    selectedOrderResults: new Set(),
    orderSortKey: "cached",
    orderSortAsc: false,
    orderActionRunning: false,
    activeBuyOrders: [],
    activeBuyOrderGroups: [],
    selectedActiveBuyOrderGroups: new Set(),
    activeOrdersLoading: false,
    activeOrderPriceQueryRunning: false,
    activeOrdersCancelling: false,
    activeOrdersLoadedAt: 0,
    activeOrdersGameFilter: "all",
    activeOrderLowestPrices: new Map(),
    historySource: "scan",
    historyMarketHashName: "",
    historyRange: "7d",
    historyRefreshing: false,
    sidebarPriceRefreshing: false,
    blLookupAppid: "",
    blLookupName: "",
  };
